### ISSUE TITLE
Umgang mit Datumswerten zwischen UI und API

### ISSUE THREAD

**Issue by simonpltzw** [simonpltzw/ffischbach-events#40]
Wer lokalisiert?

Vorteil UI
- Dynamisch an die Zeitzone des Nutzers anpassbar
  - Braucht man aber eig nicht...

Vorteil API
- Recht einfache Einstellung
- Timezone zentral festgestellt

**Comment by simonpltzw** [comment]
@lPr3dat0r Hast ne Meinung? Ich tendiere eher zur API aktuell

**Comment by lPr3dat0r** [comment]
Sorry nicht gesehen🫣, ja api
